# Generated by Django 3.0.2 on 2020-02-03 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airtickets', '0005_airplane'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField()),
                ('airportFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routesFrom', to='airtickets.Airport')),
                ('airportTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routesTo', to='airtickets.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('departureDateTime', models.DateTimeField()),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airtickets.Airplane')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airtickets.Route')),
            ],
        ),
    ]
