# Generated by Django 3.0.2 on 2020-02-03 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airtickets', '0006_flight_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_index=True, max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='flight',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=5)),
                ('price', models.FloatField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='airtickets.Flight')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='airtickets.Status')),
            ],
        ),
    ]
