# Generated by Django 3.0.2 on 2020-02-10 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airtickets', '0008_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='price',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='status',
        ),
        migrations.AddField(
            model_name='flight',
            name='duration',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='seat',
            name='airplane',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='airtickets.Airplane'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='flight',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='airtickets.Flight'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='airtickets.Seat'),
        ),
    ]
