# Generated by Django 3.0.2 on 2020-02-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtickets', '0009_auto_20200210_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.FloatField(),
        ),
    ]
