# Generated by Django 3.0.2 on 2020-02-10 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airtickets', '0010_auto_20200210_2255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='airplane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='airtickets.Airplane'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='airtickets.Flight'),
        ),
    ]
