# Generated by Django 3.0.2 on 2020-02-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtickets', '0011_auto_20200210_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='slug',
            field=models.SlugField(default='1a'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='slug',
            field=models.SlugField(default='1a'),
        ),
        migrations.AddField(
            model_name='airport',
            name='slug',
            field=models.SlugField(default='1a'),
        ),
        migrations.AddField(
            model_name='flight',
            name='slug',
            field=models.SlugField(default='1a', max_length=100),
        ),
        migrations.AddField(
            model_name='route',
            name='slug',
            field=models.SlugField(default='1a', max_length=100),
        ),
        migrations.AddField(
            model_name='seat',
            name='slug',
            field=models.SlugField(default='1a'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(default='1a', max_length=100),
        ),
    ]
